const path = require("path")
console.log(path.dirname("D:\StudyMaterial\NadosLearning\Node.js\pathModule\index.js"))
console.log(path.basename("D:\StudyMaterial\NadosLearning\Node.js\pathModule\index.js"))
console.log(path.extname("D:\StudyMaterial\NadosLearning\Node.js\pathModule\index.js"))
console.log(path.parse("D:\StudyMaterial\NadosLearning\Node.js\pathModule\index.js"))